In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB

In [2]:
dataset=pd.read_csv("heart.csv")
dataset=dataset.fillna(0)
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
labelData=dataset['target']
del dataset['target']
features=dataset.values#vector de caracteristicas
labels=labelData.values#vector de etiquetas/clases

In [4]:
import pandas
from sklearn.model_selection import KFold
import numpy as np
X = features
y = labels

In [26]:
cv = KFold(n_splits=10, random_state=0, shuffle=False)
print(cv)
gnb = GaussianNB()
scores = []
for train_index, test_index in cv.split(X):
    X_trainc, X_testc, y_trainc, y_testc = X[train_index], X[test_index], y[train_index], y[test_index]
    gnb.fit(X_trainc,y_trainc)
    predictions=gnb.predict(X_testc)
    scores.append(gnb.score(X_testc, y_testc))
    print(confusion_matrix(y_testc,predictions))
    print(classification_report(y_testc,predictions))
    print(accuracy_score(y_testc,predictions))

KFold(n_splits=10, random_state=0, shuffle=False)
[[ 0  0]
 [ 6 25]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.81      0.89        31

    accuracy                           0.81        31
   macro avg       0.50      0.40      0.45        31
weighted avg       1.00      0.81      0.89        31

0.8064516129032258
[[ 0  0]
 [ 3 28]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.90      0.95        31

    accuracy                           0.90        31
   macro avg       0.50      0.45      0.47        31
weighted avg       1.00      0.90      0.95        31

0.9032258064516129
[[ 0  0]
 [ 4 27]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.87      0.93        31

    accuracy                         

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/srv/conda/envs/notebook

In [27]:
print("Acuaraccy: ",np.mean(scores)*100,"%")

Acuaraccy:  80.47311827956989 %
